# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a anaconda pytest-cov pytest-xdist coverage sphinx_rtd_theme flake8
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - pip install -e --process-dependency-links .[dev]
  - pip install coveralls

script:
  - py.test --doctest-modules --cov=qnet_qsd src tests
after_success:
  - coveralls
