name: py36
channels:
  - defaults
dependencies:
  - python=3.6
  - anaconda
  - pip:
      - better-apidoc
      - trajectorydata
      - git+https://github.com/mabuchilab/QNET.git@develop#egg=QNET-2.0.0-dev
